
name: Grippo Blog
title: Grippo Blog
tagline: El blog oficial de Grippo.com
permalink: /:year/:month/:day/:title/index.html
# permalink: /:title.html
production_url: //blog.grippo.com
url: http://blog.grippo.com
baseurl:
feedburner: //feeds.feedburner.com/grippo
copyright: (c) 1996,2016 Grippo.com

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "CNAME", ".gitignore", ".git"]
markdown: kramdown
highlighter: rouge
paginate: 100
excerpt_separator: <!--more-->

disqus_comments: false
facebook_comments: true
disqus_shortname: grippo
facebook_app_id: 40012982943
google_analytics_id: UA-137745-1
google_analytics_domain: grippo.com
google_cse_id: 3775041682
google_partner_pub: partner-pub-2290933460302426
google_ads_lu1: false
google_ads_1: false
google_ads_5: false
google_ads_9: false
facebook_page_url: https://www.facebook.com/anuncios.grippo

firebase_url: https://hitscounter.firebaseio.com
firebase_table: blog

gems: [jekyll-paginate]
plugins: [jekyll-paginate]

author:
  name: Jorge Grippo
  email: webmaster@grippo.com
  github: grippo
  twitter: grippo
