# https://www.favicon-generator.org/
name: Grippo Blog
tagline: El blog oficial de Grippo.com
url: https://blog.grippo.com
copyright: (c) 1996,2019 Grippo.com
permalink: /:year/:month/:day/:title/index.html
feedburner: //feeds.feedburner.com/grippo

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "CNAME", ".gitignore", ".git"]
markdown: kramdown
highlighter: rouge
paginate: 100
excerpt_separator: <!--more-->

disqus_comments: false
disqus_shortname: grippo

facebook_page_url: https://www.facebook.com/anuncios.grippo
facebook_comments: true

google_analytics_id: UA-137745-1
google_analytics_domain: blog.grippo.com
google_cse_id: 3775041682
google_partner_pub: partner-pub-2290933460302426
google_ads_lu1: false
google_ads_1: false
google_ads_5: false
google_ads_9: false

firebase_url: https://hitscounter.firebaseio.com
firebase_table: blog

plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed

author:
  name: Jorge Grippo
  email: webmaster@grippo.com
  github: grippo
  twitter: grippo
