
name: Psico Notas
title: Psiconotas.com
tagline: Blog de psicolog&iacute;a, psiquiatr&iacute;a y psicoan&aacute;lisis
permalink: /:title.html
production_url: //www.psiconotas.com
url: http://www.psiconotas.com
cdn_url: //d7zeocn4055cf.cloudfront.net
feedburner: http://feeds.feedburner.com/psiconotas
copyright: (c) 1996,2016 Grippo.com

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "CNAME", ".gitignore", ".git"]
markdown: kramdown
highlighter: pygments
paginate: 100
excerpt_separator: <!--more-->

disqus_comments: false
disqus_shortname: psiconotas
facebook_comments: true
facebook_app_id: 116795527823
google_analytics_id: UA-137745-18
google_analytics_domain: psiconotas.com
google_cse_id: 8858899280
google_partner_pub: partner-pub-2290933460302426
google_ads_lu1: true
google_ads_1: true
google_ads_5: true
google_ads_9: true
facebook_page_url: https://www.facebook.com/psiconotas

firebase_url: https://hitscounter.firebaseio.com
firebase_table: psiconotas

gems: [jekyll-paginate]

author:
  name: Jorge Grippo
  email: webmaster@grippo.com
  github: grippo
  twitter: grippo


theme: jekyll-theme-cayman